### ISSUE TITLE
Crash on debian

### ISSUE THREAD

**Issue by Ocawesome101** [MCHPR/MCHPRS#26]
Don't have a lot of time, will update this later.  It does this in release mode also.

Backtrace:
```
   Compiling mchprs v0.3.0 (/home/oliver/mchprs)
    Finished dev [unoptimized + debuginfo] target(s) in 2.91s
     Running `target/debug/mchprs`
[2020-12-21 02:29:54][mchprs::server][INFO] Starting server...
[2020-12-21 02:29:54][mchprs::server][ERROR] panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 98, kind: AddrInUse, message: "Address already in use" }', src/network/mod.rs:97:56
[2020-12-21 02:29:55][mchprs::server][INFO] Done! Start took 796.341627ms
[2020-12-21 02:29:55][mchprs::server][ERROR] panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 98, kind: AddrInUse, message: "Address already in use" }', src/network/mod.rs:97:56
   0: mchprs::server::MinecraftServer::run::{{closure}}
             at src/server.rs:144
   1: std::panicking::rust_panic_with_hook
             at /rustc/1f5bc176b0e54a8e464704adcd7e571700207fe9/library/std/src/panicking.rs:595
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/1f5bc176b0e54a8e464704adcd7e571700207fe9/library/std/src/panicking.rs:497
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/1f5bc176b0e54a8e464704adcd7e571700207fe9/library/std/src/sys_common/backtrace.rs:141
   4: rust_begin_unwind
             at /rustc/1f5bc176b0e54a8e464704adcd7e571700207fe9/library/std/src/panicking.rs:493
   5: core::panicking::panic_fmt
             at /rustc/1f5bc176b0e54a8e464704adcd7e571700207fe9/library/core/src/panicking.rs:92
   6: core::option::expect_none_failed
             at /rustc/1f5bc176b0e54a8e464704adcd7e571700207fe9/library/core/src/option.rs:1268
   7: core::result::Result<T,E>::unwrap
             at /rustc/1f5bc176b0e54a8e464704adcd7e571700207fe9/library/core/src/result.rs:973
   8: mchprs::network::NetworkServer::listen
             at src/network/mod.rs:97
   9: mchprs::network::NetworkServer::new::{{closure}}
             at src/network/mod.rs:127
  10: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/1f5bc176b0e54a8e464704adcd7e571700207fe9/library/std/src/sys_common/backtrace.rs:125
  11: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}
             at /rustc/1f5bc176b0e54a8e464704adcd7e571700207fe9/library/std/src/thread/mod.rs:474
  12: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/1f5bc176b0e54a8e464704adcd7e571700207fe9/library/std/src/panic.rs:322
  13: std::panicking::try::do_call
             at /rustc/1f5bc176b0e54a8e464704adcd7e571700207fe9/library/std/src/panicking.rs:379
  14: __rust_try
  15: std::panicking::try
             at /rustc/1f5bc176b0e54a8e464704adcd7e571700207fe9/library/std/src/panicking.rs:343
  16: std::panic::catch_unwind
             at /rustc/1f5bc176b0e54a8e464704adcd7e571700207fe9/library/std/src/panic.rs:396
  17: std::thread::Builder::spawn_unchecked::{{closure}}
             at /rustc/1f5bc176b0e54a8e464704adcd7e571700207fe9/library/std/src/thread/mod.rs:473
  18: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/1f5bc176b0e54a8e464704adcd7e571700207fe9/library/core/src/ops/function.rs:227
  19: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/1f5bc176b0e54a8e464704adcd7e571700207fe9/library/alloc/src/boxed.rs:1328
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/1f5bc176b0e54a8e464704adcd7e571700207fe9/library/alloc/src/boxed.rs:1328
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/1f5bc176b0e54a8e464704adcd7e571700207fe9/library/std/src/sys/unix/thread.rs:71
  20: start_thread
  21: clone

[2020-12-21 02:29:55][mchprs::server][ERROR] panicked at 'Client receiver channel disconnected!', src/network/mod.rs:140:21
[2020-12-21 02:29:55][mchprs::server][ERROR] panicked at 'Client receiver channel disconnected!', src/network/mod.rs:140:21
   0: mchprs::server::MinecraftServer::run::{{closure}}
             at src/server.rs:144
   1: std::panicking::rust_panic_with_hook
             at /rustc/1f5bc176b0e54a8e464704adcd7e571700207fe9/library/std/src/panicking.rs:595
   2: std::panicking::begin_panic::{{closure}}
             at /rustc/1f5bc176b0e54a8e464704adcd7e571700207fe9/library/std/src/panicking.rs:520
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/1f5bc176b0e54a8e464704adcd7e571700207fe9/library/std/src/sys_common/backtrace.rs:141
   4: std::panicking::begin_panic
             at /rustc/1f5bc176b0e54a8e464704adcd7e571700207fe9/library/std/src/panicking.rs:519
   5: mchprs::network::NetworkServer::update
             at src/network/mod.rs:140
   6: mchprs::server::MinecraftServer::update
             at src/server.rs:596
   7: mchprs::server::MinecraftServer::run
             at src/server.rs:200
   8: mchprs::main
             at src/main.rs:4
   9: core::ops::function::FnOnce::call_once
             at /rustc/1f5bc176b0e54a8e464704adcd7e571700207fe9/library/core/src/ops/function.rs:227
  10: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/1f5bc176b0e54a8e464704adcd7e571700207fe9/library/std/src/sys_common/backtrace.rs:125
  11: std::rt::lang_start::{{closure}}
             at /rustc/1f5bc176b0e54a8e464704adcd7e571700207fe9/library/std/src/rt.rs:66
  12: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/1f5bc176b0e54a8e464704adcd7e571700207fe9/library/core/src/ops/function.rs:259
      std::panicking::try::do_call
             at /rustc/1f5bc176b0e54a8e464704adcd7e571700207fe9/library/std/src/panicking.rs:379
      std::panicking::try
             at /rustc/1f5bc176b0e54a8e464704adcd7e571700207fe9/library/std/src/panicking.rs:343
      std::panic::catch_unwind
             at /rustc/1f5bc176b0e54a8e464704adcd7e571700207fe9/library/std/src/panic.rs:396
      std::rt::lang_start_internal
             at /rustc/1f5bc176b0e54a8e464704adcd7e571700207fe9/library/std/src/rt.rs:51
  13: std::rt::lang_start
             at /rustc/1f5bc176b0e54a8e464704adcd7e571700207fe9/library/std/src/rt.rs:65
  14: main
  15: __libc_start_main
  16: _start
```

**Comment by StackDoubleFlow** [comment]
Check to see that you have no other programs (minecraft servers and such) that are binding to the same port. (by default this is 25565, to change this you can go into the `Config.toml` file which should have been generated)

**Comment by Ocawesome101** [comment]
Yeah, it was a port issue.  I already have a server on port 25565, set MCHPRS to 25585 and it's all good :)
